<a href="https://colab.research.google.com/github/ShubhamCJagtap/Capstone_Project_1_EDA/blob/master/Delhi_dataset_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [76]:
import pandas as pd
import numpy as np
#import mysql.connector as connection # install !pip install mysql.connector
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

pd.set_option('display.max_columns',None)
pd.set_option('display.max_rows',None)
pd.set_option('display.max_colwidth',None)
pd.set_option('mode.chained_assignment',None)

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [77]:
df1 = pd.read_csv('/content/drive/MyDrive/Capstone 1 Insaid/Database/events_data.csv')

In [78]:
df2 = pd.read_csv('https://raw.githubusercontent.com/ShubhamCJagtap/Capstone_Project_1_EDA/master/gender_age.csv')

In [79]:
df3 = pd.read_csv('https://raw.githubusercontent.com/ShubhamCJagtap/Capstone_Project_1_EDA/master/phone_brand_device_model.csv')

In [80]:
df1.columns

Index(['event_id', 'device_id', 'timestamp', 'longitude', 'latitude', 'city',
       'state'],
      dtype='object')

In [81]:
cities = (df1[df1['state']=='Delhi']['city'].unique()).tolist()

In [82]:
cities

['Delhi',
 'SultanpurMajra',
 'Deoli',
 'NiDilli',
 'RoshanPura',
 'BhalswaJahangirpur',
 'Gokalpur',
 'Tigri',
 'DilliCantonment',
 'NangloiJat']

In [9]:
len(cities)

10

In [83]:
df_cities = df1[(df1['city']==cities[0])|
    (df1['city']==cities[1])|
    (df1['city']==cities[2])|
    (df1['city']==cities[3])|
    (df1['city']==cities[4])|
    (df1['city']==cities[5])|
    (df1['city']==cities[6])|
    (df1['city']==cities[7])|
    (df1['city']==cities[8])|
    (df1['city']==cities[9])]

In [84]:
df_cities['city'].unique(),df_cities['state'].unique()

(array(['Delhi', 'SultanpurMajra', 'Deoli', 'NiDilli', 'RoshanPura',
        'BhalswaJahangirpur', 'Gokalpur', 'Tigri', 'DilliCantonment',
        'NangloiJat'], dtype=object), array(['Delhi', nan], dtype=object))

In [85]:
df_cities.isna().sum()

event_id      0
device_id    69
timestamp     0
longitude    63
latitude     63
city          0
state        64
dtype: int64

In [86]:
df_cities[df_cities['state'].isna()].head()

event_id     device_id            timestamp  longitude  latitude  \
58711    1586328 -6.242501e+18  2016-05-02 18:25:36  77.293991  28.74982   
146029    191851 -6.242501e+18  2016-05-02 05:50:53  77.293991  28.74982   
154676   1813991 -8.340098e+18  2016-05-06 22:03:19  77.305988  28.68898   
206994   1804080 -8.340098e+18  2016-05-02 15:35:20  77.305988  28.68898   
219532    341684 -6.242501e+18  2016-05-02 08:37:46  77.293991  28.74982   

         city state  
58711   Delhi   NaN  
146029  Delhi   NaN  
154676  Delhi   NaN  
206994  Delhi   NaN  
219532  Delhi   NaN

In [87]:
df_cities['state'].fillna('Delhi',inplace=True)

In [88]:
df_cities.isna().sum(),df_cities.nunique()

(event_id      0
 device_id    69
 timestamp     0
 longitude    63
 latitude     63
 city          0
 state         0
 dtype: int64, event_id     751797
 device_id      4909
 timestamp    412099
 longitude      4795
 latitude       4789
 city             10
 state             1
 dtype: int64)

In [ ]:
df_cities.to_csv('Dataset_for_delhi.csv')

In [18]:
df_cities[(df_cities['longitude'].isna())&(df_cities['latitude'].isna())].head()

event_id     device_id            timestamp  longitude  latitude  \
8015     2929521  1.779631e+18  2016-05-05 01:15:22        NaN       NaN   
35009    1039863  5.375599e+18  2016-05-01 14:40:31        NaN       NaN   
91559    2527074  5.375599e+18  2016-05-07 17:51:23        NaN       NaN   
102308   2922517  1.779631e+18  2016-05-01 21:50:03        NaN       NaN   
119754   2869070  4.782582e+18  2016-05-01 02:35:12        NaN       NaN   

         city  state  
8015    Delhi  Delhi  
35009   Delhi  Delhi  
91559   Delhi  Delhi  
102308  Delhi  Delhi  
119754  Delhi  Delhi

In [19]:
df_cities[(df_cities['longitude'].isna())&(df_cities['latitude'].isna())].shape

(63, 7)

In [20]:
(df_cities[(df_cities['longitude'].isna())|(df_cities['latitude'].isna())]==df_cities[(df_cities['longitude'].isna())&(df_cities['latitude'].isna())]).shape

(63, 7)

In [21]:
df_cities[(df_cities['longitude'].isna())&(df_cities['latitude'].isna())&(df_cities['device_id'].isna())].shape

(0, 7)

# Fill missing values of latitude an longitude based on device ID's

In [89]:
device_id_lat_lon_missing = df_cities[(df_cities['longitude'].isna())&(df_cities['latitude'].isna())]['device_id'].unique()

In [90]:
device_id_lat_lon_missing

array([1.77963102e+18, 5.37559902e+18, 4.78258205e+18])

In [91]:
lst_id_lat_lon = []
for i in device_id_lat_lon_missing:
  a = df_cities[(df_cities['longitude'].isna()==False)&(df_cities['latitude'].isna()==False)&(df_cities['device_id']==i)][['device_id','longitude','latitude']].value_counts()
  lst_id_lat_lon.append(a.index.values)

In [104]:
id = []
lat = []
lon = []
for j in lst_id_lat_lon:
  id.append(j[0][0])
  lon.append(j[0][1])
  lat.append(j[0][2])

In [105]:
id,lat,lon

([1.7796310234394053e+18, 5.375599021847303e+18, 4.782582047729166e+18],
 [28.738901, 28.718392, 28.718379],
 [77.235416, 77.283447, 77.22522])

In [106]:
id[0]

1.7796310234394053e+18

In [122]:
df_cities.loc[(df_cities['device_id']==id[0])&(np.isnan(df_cities['latitude'])),'latitude']#.fillna(lat[0])

8015      NaN
102308    NaN
388546    NaN
603570    NaN
963156    NaN
1102363   NaN
1183044   NaN
1441367   NaN
1613563   NaN
1711195   NaN
1849716   NaN
1929965   NaN
2105900   NaN
2218433   NaN
2383992   NaN
2420466   NaN
2592269   NaN
2611807   NaN
2612236   NaN
2691692   NaN
3240057   NaN
Name: latitude, dtype: float64

In [123]:
df_cities.loc[(df_cities['device_id']==id[1])&(np.isnan(df_cities['latitude'])),'latitude']

35009     NaN
91559     NaN
181516    NaN
392144    NaN
408440    NaN
618174    NaN
761466    NaN
786473    NaN
1091491   NaN
1139239   NaN
1344039   NaN
1731090   NaN
1938824   NaN
1990928   NaN
2000548   NaN
2270111   NaN
2440981   NaN
2611126   NaN
2848235   NaN
2976687   NaN
2993381   NaN
Name: latitude, dtype: float64

In [130]:
df_cities.loc[(df_cities['device_id']==id[2])&(np.isnan(df_cities['latitude'])),'latitude'].shape

(21,)

In [132]:
for i in range(0,len(id)):
  print(df_cities.loc[(df_cities['device_id']==id[i])&(np.isnan(df_cities['latitude'])),'latitude'].shape)

(21,)
(21,)
(21,)


In [134]:
for i in range(0,len(id)):
  df_cities.loc[(df_cities['device_id']==id[i])&(np.isnan(df_cities['latitude'])),'latitude'] = lat[i]
  df_cities.loc[(df_cities['device_id']==id[i])&(np.isnan(df_cities['longitude'])),'longitude'] = lon[i]

In [135]:
df_cities.isna().sum()

event_id      0
device_id    69
timestamp     0
longitude     0
latitude      0
city          0
state         0
dtype: int64

In [139]:
print(df_cities.loc[(df_cities['device_id']==id[0])&(np.isnan(df_cities['latitude'])),'latitude'],
df_cities.loc[(df_cities['device_id']==id[1])&(np.isnan(df_cities['latitude'])),'latitude'],
df_cities.loc[(df_cities['device_id']==id[2])&(np.isnan(df_cities['latitude'])),'latitude'])

Series([], Name: latitude, dtype: float64) Series([], Name: latitude, dtype: float64) Series([], Name: latitude, dtype: float64)


## Apply same logic to fill device Id's

In [144]:
device_id_missing_lon = df_cities[df_cities['device_id'].isna()]['longitude'].unique()
device_id_missing_lat = df_cities[df_cities['device_id'].isna()]['latitude'].unique()

In [145]:
device_id_missing_lon

array([77.292481, 77.274814, 77.303153])

In [146]:
device_id_missing_lat

array([28.719966, 28.721053, 28.728888])

In [152]:
lst_id_lon = []
for i in device_id_missing_lon:
  a = df_cities[(df_cities['device_id'].isna()==False)&(df_cities['longitude']==i)][['device_id','longitude','latitude']].value_counts()
  lst_id_lon.append(a.index.values)

In [155]:
lst_id_lon

[array([(5.098778421671838e+18, 77.29248100000002, 28.719966000000003)],
       dtype=object),
 array([(3.724654925765159e+18, 77.27481399999998, 28.721053)],
       dtype=object),
 array([(-6.875585507485886e+18, 77.30315300000002, 28.728888)],
       dtype=object)]

In [151]:
lst_id_lat = []
for i in device_id_missing_lat:
  a = df_cities[(df_cities['device_id'].isna()==False)&(df_cities['latitude']==i)][['device_id','longitude','latitude']].value_counts()
  lst_id_lat.append(a.index.values)

In [154]:
lst_id_lat

[array([(5.098778421671838e+18, 77.29248100000002, 28.719966000000003)],
       dtype=object),
 array([(3.724654925765159e+18, 77.27481399999998, 28.721053)],
       dtype=object),
 array([(-6.875585507485886e+18, 77.30315300000002, 28.728888)],
       dtype=object)]

In [156]:
id_lat = []
lat_lat = []
lon_lat = []
for j in lst_id_lat:
  id_lat.append(j[0][0])
  lon_lat.append(j[0][1])
  lat_lat.append(j[0][2])

In [158]:
id_lat,lat_lat,lon_lat

([5.098778421671838e+18, 3.724654925765159e+18, -6.875585507485886e+18],
 [28.719966000000003, 28.721053, 28.728888],
 [77.29248100000002, 77.27481399999998, 77.30315300000002])

In [159]:
id_lon = []
lat_lon = []
lon_lon = []
for j in lst_id_lat:
  id_lon.append(j[0][0])
  lon_lon.append(j[0][1])
  lat_lon.append(j[0][2])

In [160]:
id_lon,lat_lon,lon_lon

([5.098778421671838e+18, 3.724654925765159e+18, -6.875585507485886e+18],
 [28.719966000000003, 28.721053, 28.728888],
 [77.29248100000002, 77.27481399999998, 77.30315300000002])

In [164]:
df_cities.loc[(df_cities['latitude']==lat_lat[0])&(np.isnan(df_cities['device_id'])),'device_id']

72898     NaN
278170    NaN
350761    NaN
554548    NaN
598793    NaN
600849    NaN
698069    NaN
740873    NaN
890505    NaN
1287193   NaN
1563172   NaN
1841116   NaN
1851327   NaN
1908542   NaN
1939918   NaN
1987919   NaN
2102325   NaN
2450556   NaN
2845240   NaN
2939178   NaN
3146530   NaN
3175200   NaN
3192090   NaN
Name: device_id, dtype: float64

In [167]:
for i in range(0,len(id_lat)):
  df_cities.loc[(df_cities['latitude']==lat_lat[i])&(np.isnan(df_cities['device_id'])),'device_id'] = id_lat[i]

In [168]:
df_cities.isna().sum()

event_id     0
device_id    0
timestamp    0
longitude    0
latitude     0
city         0
state        0
dtype: int64

## All missing values from first dataset wrt delhi city are filled

In [169]:
df_cities.head()

event_id     device_id            timestamp  longitude   latitude   city  \
0    2765368  2.973348e+18  2016-05-07 22:52:05  77.225676  28.730140  Delhi   
2     605968 -3.264500e+18  2016-05-02 14:23:04  77.256809  28.757906  Delhi   
8    2309828  3.020769e+18  2016-05-04 09:24:50  77.263922  28.757914  Delhi   
13   2633127 -3.090167e+18  2016-05-05 04:42:59  77.285920  28.758381  Delhi   
17   2224400  7.566051e+18  2016-05-01 00:07:47  77.240478  28.715664  Delhi   

    state  
0   Delhi  
2   Delhi  
8   Delhi  
13  Delhi  
17  Delhi